### ISSUE TITLE
[BR] "An error occurred  This appears to be an attack. Kindly retry"

### ISSUE THREAD

**Issue by RoneoOrg** [Hrishikesh-K/netlify-file-browser#1]
> The bug I'm reporting is not already listed as a limitation on the home page

Yes

> The deploy ID with the problem is

The error occurs right after the panel "Authorize Application" on Netlify. I had no time to select a deploy / project.

Detail of the page:

```
Authorize Application

An application named Netlify File Browser is asking for permission to access Netlify on your behalf.

This app will be able to create and manage sites in your Netlify teams. You can revoke access at any time.

Please review the details below before authorizing access:

Redirect URI
    https://netlify-file-browser.netlify.app
Description
    Preview or download your deploys easily with Netlify File Browser
```

* Desktop:
  - OS: Debian 10
  - Browser: Firefox
  - Version: 78.15.0esr (64 bits)

**Additional context:**

This happened right after I Authorized the application with a Github login.
So I tried also with an email login and the same error appeared

The console of Firefox reads (in french - I can provide a translation if required):

```
La connexion avec https://clientstream.launchdarkly.com/eval/5e42e94d6bd2ec08061adf53/eyJrZXkiOiI2MGMwZDc0ZjM4Mjg5YzFkNzZmNmMwNWQiLCJlbWFpbCI6ImlhZWlvdUByaXNldXAubmV0IiwiY3VzdG9tIjp7ImN1cnJlbnRfYWNjb3VudF9pZCI6IjYwYzBkNzRmMzgyODljMWQ3NmY2YzA1ZSIsImN1cnJlbnRfcGxhbl90eXBlIjoic3RhcnRlci1wbHVzIn19 a été interrompue pendant le chargement de la page. app.bundle.js:2239:132378
LD: [warn] Error on stream connection: {"isTrusted":true}, will continue retrying every 1000 milliseconds. app.bundle.js:15:6160
Erreur dans les liens source : Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL de la ressource : https://app.netlify.com/app.bundle.js
URL du lien source : app.bundle.js.map
```

**Comment by RoneoOrg** [comment]
Update: I tried in Firefox Private Mode (to exclude Addon incompatibility) and the same error appears

**Comment by Hrishikesh-K** [comment]
The app sets a state in `localstorage` when you try to Authorize with Netlify. This is to prevent CSRF attacks of someone pretending to be my app to try to get you to login to Netlify. The error would occur when you authorise from Netlify but there's either no state set or the state that's set is not the one returned by Netlify.

This should never happen when you're clicking the authorize button in the app.

Just to be sure, you're logging into Netlify before trying to use this app, correct?

**Comment by RoneoOrg** [comment]
> Just to be sure, you're logging into Netlify before trying to use this app, correct?

Yes, but Netlify asks me to reconnect regularly on Firefox, no idea where it comes from and if it's related

**Comment by Hrishikesh-K** [comment]
Yes, Netlify UI will make you authorise the app every time. Would you be able to use the JS debugger in the browser to add breakpoints to see if the state that's stored in the `localstorage` is same as the state being returned by Netlify UI in the URL that brings you back to the app?

If not debugger, I believe you could also try this by setting network conditions to have a very very slow speed so that you get time to check before the application does anything.

**Comment by RoneoOrg** [comment]
With slow network and in Private Mode the only new thing I spotted is this error on Netlify login page (even before to reach netlify-file-browser):

```
Certains cookies utilisent incorrectement l’attribut recommandé « sameSite » 4
La ressource à l’adresse « <URL> » a été bloquée car le blocage de contenu est activé. 9
[bugsnag] Loaded! app.bundle.js:16:10352
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.segment.io/v1/p. Raison : échec de la requête CORS.
2
Content Security Policy: « x-frame-options » ignoré en raison de la directive « frame-ancestors ».
Erreur dans les liens source : Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL de la ressource : https://app.netlify.com/app.bundle.js
URL du lien source : app.bundle.js.map

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.segment.io/v1/p. Raison : échec de la requête CORS.
```

I'm not familiar with JS debugger, so I guess I'll give up for now and inspect my Firefox settings later

**Comment by Hrishikesh-K** [comment]
Those logs are from Netlify UI and it's normal to have them. I'll try to setup a Debian VM and see if I can reproduce it.

**Comment by Hrishikesh-K** [comment]
Update: I just had a fresh installation of Debian and I can'r reproduce the error.

https://user-images.githubusercontent.com/11403551/139521174-7ff0d75c-cbd9-4e32-b279-e6c305d8327c.mp4


I'd suggest try a different browser or device. If that doesn't change anything, well I'll need to see it happen myself. Possibly, try sending a screen recording with the dev tools open in which I can see the `localstorage` being populated by the state and the Netlify UI returning the state back to the app.

**Comment by Hrishikesh-K** [comment]
Closing as it lacks reproduction. Feel free to re-open if there's some additional insights to add to this.
